# Uncomment the next line to define a global platform for your project
 source 'https://github.com/CocoaPods/Specs.git'
 platform :ios, '11.0'

target 'Capstone' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Latest release in CocoaPods
  pod 'SwipeCellKit'
  pod 'MessageKit'
  pod 'MessageInputBar'
  pod 'SparrowKit'
  pod 'SPStorkController'
  pod 'PusherChatkit'
end

